language: generic

sudo: required

services:
  - docker

before_install: 
  - docker build -t tamiilore/docker-react -f Dockerfile.dev .

script: 
  - docker run -e tamiilore/docker-react CI=true tamiilore/docker-react npm run test