language: generic
sudo: required
services:
  - docker
before_install: 
  - docker build -t tamiilore/docker-react -f Dockerfile.dev .
script: 
  - docker run tamiilore/docker-react npm run test -- --coverage
  